<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWPq4zJM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWPq4zJM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWPq4zJM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWPq4zJM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWPq4zJM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WPq4zJM',
    'container.build_id' => '6dba4c5b',
    'container.build_time' => 1608047504,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWPq4zJM');
